spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erp_ventas
    username: postgres
    password: 4815162342

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081